function fpath = simname(eps, d, l, rho, v, Kagar, Kstiff, rev, run, fp)
    uname = getenv("LOGNAME");
    fpath = sprintf(['/scratch/gpfs/' uname '/lammps-myxo-data/%s/'  ...
        'eps%03d/' ...
        'd%04d/' ...
        'l%04d/' ...
        'rho%04d/' ...
        'v%04d/' ...
        'Kagar%03d/' ...
        'Kstiff%03d/' ...
        'rev%03d/' ...
        'run_%03d/'], ...
        fp, eps, d*100, l*100, rho*100, v*100, Kagar, Kstiff, rev, run);
end
